### ISSUE TITLE
1.10.1: Fatal: directory lib/ieee.08 already exists and is not an NVC library

### ISSUE THREAD

**Issue by yurivict** [nickg/nvc#746]
Build fails:
```
--- lib/ieee.08/IEEE.MATH_REAL ---
** Fatal: directory lib/ieee.08 already exists and is not an NVC library
*** [lib/ieee.08/IEEE.MATH_REAL] Error code 1
```

clang-15
FreeBSD 13.2

**Comment by nickg** [comment]
I can't reproduce this. I tried manually updating the version in `/usr/ports/cad/nvc/Makefile` to 1.10.1 but it built ok. Maybe try disabling `-j` or use `MAKE=gmake`?

**Comment by yurivict** [comment]
```-j 1``` helped, thanks.

But it looks like there is some dependency problem though.
It might depend on versions of some other packages. Maybe the gmake version.

**Comment by m42uko** [comment]
I can confirm this also happens **sometimes** on Linux (ArchLinux, Linux kronii 6.4.11-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 19 Aug 2023 15:38:34 +0000 x86_64 GNU/Linux) when using a high core count to compile. Seems to be some kind of race condition.

**Comment by nickg** [comment]
I think the problem is that creating the library involves two steps: 1) making the directory and 2) creating the `_NVC_LIB` file within it which is used as a lock file.  If two processes attempt to concurrently create the same library it's possible for one of them to observe the intermediate state between 1 and 2 where the library exists but the lock file doesn't and then report this error. Should be fixed by the commit above.
